// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: myprocam

#ifndef UI_GALLERY1_H
#define UI_GALLERY1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Gallery1
extern void ui_Gallery1_screen_init(void);
extern void ui_Gallery1_screen_destroy(void);
extern lv_obj_t *ui_Gallery1;
extern lv_obj_t *ui_imagepreview;
extern void ui_event_back2( lv_event_t * e);
extern lv_obj_t *ui_back2;
extern lv_obj_t *ui_Image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

