// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: myprocam

#include "../ui.h"

lv_obj_t *ui_Gallery1 = NULL;lv_obj_t *ui_imagepreview = NULL;lv_obj_t *ui_back2 = NULL;lv_obj_t *ui_Image4 = NULL;
// event funtions
void ui_event_back2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_main_screen_init);
}
}

// build funtions

void ui_Gallery1_screen_init(void)
{
ui_Gallery1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Gallery1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Gallery1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Gallery1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imagepreview = lv_obj_create(ui_Gallery1);
lv_obj_remove_style_all(ui_imagepreview);
lv_obj_set_width( ui_imagepreview, 480);
lv_obj_set_height( ui_imagepreview, 800);
lv_obj_set_align( ui_imagepreview, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_imagepreview, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back2 = lv_btn_create(ui_Gallery1);
lv_obj_set_width( ui_back2, 71);
lv_obj_set_height( ui_back2, 80);
lv_obj_set_x( ui_back2, -201 );
lv_obj_set_y( ui_back2, 356 );
lv_obj_set_align( ui_back2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_back2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_back2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_back2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_back2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_back2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_back2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image4 = lv_img_create(ui_back2);
lv_img_set_src(ui_Image4, &ui_img_2105778884);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 438
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 269
lv_obj_set_x( ui_Image4, -7 );
lv_obj_set_y( ui_Image4, 5 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image4,30);

lv_obj_add_event_cb(ui_back2, ui_event_back2, LV_EVENT_ALL, NULL);

}

void ui_Gallery1_screen_destroy(void)
{
   if (ui_Gallery1) lv_obj_del(ui_Gallery1);

// NULL screen variables
ui_Gallery1= NULL;
ui_imagepreview= NULL;
ui_back2= NULL;
ui_Image4= NULL;

}
