// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: myprocam

#include "../ui.h"

lv_obj_t *uic_Screen1;
lv_obj_t *ui_main = NULL;lv_obj_t *ui_MENU = NULL;lv_obj_t *ui_Label13 = NULL;lv_obj_t *ui_Label12 = NULL;lv_obj_t *ui_INFOSONSCREEN = NULL;lv_obj_t *ui_Btnbackdrop = NULL;lv_obj_t *ui_QUICKSETTINGSOVERLAY = NULL;lv_obj_t *ui_ISO = NULL;lv_obj_t *ui_SHUTTER = NULL;lv_obj_t *ui_back = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_GRIDSWITCH = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_DIGITALLEVELSWITCH = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_COLOUR = NULL;lv_obj_t *ui_FLASHSETTINGS = NULL;lv_obj_t *ui_Button2 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Button1 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Button3 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_GALLERY = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_SETTINGS = NULL;lv_obj_t *ui_Label11 = NULL;
// event funtions
void ui_event_main( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_flag_modify( ui_INFOSONSCREEN, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_MENU, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_Btnbackdrop, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_QUICKSETTINGSOVERLAY, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_MENU( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_QUICKSETTINGSOVERLAY, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Btnbackdrop, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_MENU, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_INFOSONSCREEN, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_Btnbackdrop( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_QUICKSETTINGSOVERLAY, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Btnbackdrop, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_MENU, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_INFOSONSCREEN, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_back( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_QUICKSETTINGSOVERLAY, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Btnbackdrop, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_MENU, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_INFOSONSCREEN, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_GALLERY( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Gallery1, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_Gallery1_screen_init);
}
}

void ui_event_SETTINGS( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_main_screen_init);
}
}

// build funtions

void ui_main_screen_init(void)
{
ui_main = lv_obj_create(NULL);
lv_obj_clear_flag( ui_main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_main, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_opa(ui_main, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MENU = lv_btn_create(ui_main);
lv_obj_set_width( ui_MENU, 86);
lv_obj_set_height( ui_MENU, 33);
lv_obj_set_x( ui_MENU, 192 );
lv_obj_set_y( ui_MENU, -381 );
lv_obj_set_align( ui_MENU, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MENU, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MENU, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MENU, 13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MENU, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MENU, 180, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_MENU, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_MENU);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -31 );
lv_obj_set_y( ui_Label13, -6 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,".");
lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label13, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_MENU);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, 4 );
lv_obj_set_y( ui_Label12, 1 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"MENU");
lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x484848), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_INFOSONSCREEN = lv_obj_create(ui_main);
lv_obj_set_width( ui_INFOSONSCREEN, 375);
lv_obj_set_height( ui_INFOSONSCREEN, 21);
lv_obj_set_x( ui_INFOSONSCREEN, -47 );
lv_obj_set_y( ui_INFOSONSCREEN, -385 );
lv_obj_set_align( ui_INFOSONSCREEN, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_INFOSONSCREEN, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_INFOSONSCREEN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_INFOSONSCREEN, 180, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_INFOSONSCREEN, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Btnbackdrop = lv_btn_create(ui_main);
lv_obj_set_width( ui_Btnbackdrop, 480);
lv_obj_set_height( ui_Btnbackdrop, 800);
lv_obj_set_align( ui_Btnbackdrop, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Btnbackdrop, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Btnbackdrop, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Btnbackdrop, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Btnbackdrop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Btnbackdrop, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Btnbackdrop, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_QUICKSETTINGSOVERLAY = lv_obj_create(ui_main);
lv_obj_set_width( ui_QUICKSETTINGSOVERLAY, 261);
lv_obj_set_height( ui_QUICKSETTINGSOVERLAY, 602);
lv_obj_set_x( ui_QUICKSETTINGSOVERLAY, 106 );
lv_obj_set_y( ui_QUICKSETTINGSOVERLAY, -95 );
lv_obj_set_align( ui_QUICKSETTINGSOVERLAY, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_QUICKSETTINGSOVERLAY, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_QUICKSETTINGSOVERLAY, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_QUICKSETTINGSOVERLAY, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_QUICKSETTINGSOVERLAY, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_QUICKSETTINGSOVERLAY, 220, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_QUICKSETTINGSOVERLAY, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_outline_width(ui_QUICKSETTINGSOVERLAY, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_QUICKSETTINGSOVERLAY, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_QUICKSETTINGSOVERLAY, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_QUICKSETTINGSOVERLAY, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_QUICKSETTINGSOVERLAY, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_QUICKSETTINGSOVERLAY, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_ISO = lv_slider_create(ui_QUICKSETTINGSOVERLAY);
lv_slider_set_value( ui_ISO, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_ISO)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_ISO, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_ISO, 218);
lv_obj_set_height( ui_ISO, 11);
lv_obj_set_x( ui_ISO, 5 );
lv_obj_set_y( ui_ISO, -215 );
lv_obj_set_align( ui_ISO, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_ISO, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ISO, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ISO, lv_color_hex(0x00CA00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ISO, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ISO, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ISO, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_SHUTTER = lv_slider_create(ui_QUICKSETTINGSOVERLAY);
lv_slider_set_value( ui_SHUTTER, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SHUTTER)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SHUTTER, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SHUTTER, 218);
lv_obj_set_height( ui_SHUTTER, 11);
lv_obj_set_x( ui_SHUTTER, 5 );
lv_obj_set_y( ui_SHUTTER, -150 );
lv_obj_set_align( ui_SHUTTER, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SHUTTER, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SHUTTER, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SHUTTER, lv_color_hex(0x00CA00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SHUTTER, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SHUTTER, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SHUTTER, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_back = lv_btn_create(ui_QUICKSETTINGSOVERLAY);
lv_obj_set_width( ui_back, 86);
lv_obj_set_height( ui_back, 40);
lv_obj_set_x( ui_back, 84 );
lv_obj_set_y( ui_back, -277 );
lv_obj_set_align( ui_back, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_back, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_back, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_back, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_back, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_back, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_back, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_back);
lv_img_set_src(ui_Image3, &ui_img_2105778884);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 438
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 269
lv_obj_set_x( ui_Image3, 20 );
lv_obj_set_y( ui_Image3, -4 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Image3,1800);
lv_img_set_zoom(ui_Image3,19);

ui_Label3 = lv_label_create(ui_QUICKSETTINGSOVERLAY);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 0 );
lv_obj_set_y( ui_Label3, -237 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"ISO");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_QUICKSETTINGSOVERLAY);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 0 );
lv_obj_set_y( ui_Label1, -174 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"SHUTTER");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GRIDSWITCH = lv_switch_create(ui_QUICKSETTINGSOVERLAY);
lv_obj_set_width( ui_GRIDSWITCH, 64);
lv_obj_set_height( ui_GRIDSWITCH, 23);
lv_obj_set_x( ui_GRIDSWITCH, 82 );
lv_obj_set_y( ui_GRIDSWITCH, -87 );
lv_obj_set_align( ui_GRIDSWITCH, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_GRIDSWITCH, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GRIDSWITCH, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_GRIDSWITCH, lv_color_hex(0x00CA00), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_GRIDSWITCH, 255, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_GRIDSWITCH, lv_color_hex(0x00CA00), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_GRIDSWITCH, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_Label2 = lv_label_create(ui_QUICKSETTINGSOVERLAY);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -44 );
lv_obj_set_y( ui_Label2, -86 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"GRID OVERLAY");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DIGITALLEVELSWITCH = lv_switch_create(ui_QUICKSETTINGSOVERLAY);
lv_obj_set_width( ui_DIGITALLEVELSWITCH, 64);
lv_obj_set_height( ui_DIGITALLEVELSWITCH, 23);
lv_obj_set_x( ui_DIGITALLEVELSWITCH, 82 );
lv_obj_set_y( ui_DIGITALLEVELSWITCH, -34 );
lv_obj_set_align( ui_DIGITALLEVELSWITCH, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_DIGITALLEVELSWITCH, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DIGITALLEVELSWITCH, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_DIGITALLEVELSWITCH, lv_color_hex(0x00CA00), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_DIGITALLEVELSWITCH, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_Label4 = lv_label_create(ui_QUICKSETTINGSOVERLAY);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -44 );
lv_obj_set_y( ui_Label4, -35 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"DIGITAL LEVEL");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_COLOUR = lv_slider_create(ui_QUICKSETTINGSOVERLAY);
lv_slider_set_value( ui_COLOUR, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_COLOUR)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_COLOUR, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_COLOUR, 218);
lv_obj_set_height( ui_COLOUR, 11);
lv_obj_set_x( ui_COLOUR, 5 );
lv_obj_set_y( ui_COLOUR, 140 );
lv_obj_set_align( ui_COLOUR, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_COLOUR, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_COLOUR, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_COLOUR, lv_color_hex(0xFFC71B), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_COLOUR, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_COLOUR, lv_color_hex(0x03C8FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_COLOUR, LV_GRAD_DIR_HOR, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_COLOUR, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_COLOUR, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_FLASHSETTINGS = lv_obj_create(ui_QUICKSETTINGSOVERLAY);
lv_obj_set_width( ui_FLASHSETTINGS, 231);
lv_obj_set_height( ui_FLASHSETTINGS, 32);
lv_obj_set_x( ui_FLASHSETTINGS, 0 );
lv_obj_set_y( ui_FLASHSETTINGS, 50 );
lv_obj_set_align( ui_FLASHSETTINGS, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FLASHSETTINGS, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_FLASHSETTINGS, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_FLASHSETTINGS, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FLASHSETTINGS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_FLASHSETTINGS, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_btn_create(ui_FLASHSETTINGS);
lv_obj_set_width( ui_Button2, 75);
lv_obj_set_height( ui_Button2, 27);
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x00CA00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Button2, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x00CA00), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Label7 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"AUTO");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_FLASHSETTINGS);
lv_obj_set_width( ui_Button1, 75);
lv_obj_set_height( ui_Button1, 27);
lv_obj_set_x( ui_Button1, -75 );
lv_obj_set_y( ui_Button1, 0 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Button1, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x00CA00), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Label6 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"ON");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_btn_create(ui_FLASHSETTINGS);
lv_obj_set_width( ui_Button3, 75);
lv_obj_set_height( ui_Button3, 27);
lv_obj_set_x( ui_Button3, 75 );
lv_obj_set_y( ui_Button3, 0 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Button3, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x00CA00), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Label5 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"OFF");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_QUICKSETTINGSOVERLAY);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -1 );
lv_obj_set_y( ui_Label8, 12 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"FLASH");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_QUICKSETTINGSOVERLAY);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 0 );
lv_obj_set_y( ui_Label9, 113 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"COLOUR");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GALLERY = lv_btn_create(ui_QUICKSETTINGSOVERLAY);
lv_obj_set_width( ui_GALLERY, 227);
lv_obj_set_height( ui_GALLERY, 32);
lv_obj_set_x( ui_GALLERY, 0 );
lv_obj_set_y( ui_GALLERY, 205 );
lv_obj_set_align( ui_GALLERY, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_GALLERY, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_GALLERY, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_GALLERY, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GALLERY, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_GALLERY, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_GALLERY);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"GALLERY");
lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label10, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SETTINGS = lv_btn_create(ui_QUICKSETTINGSOVERLAY);
lv_obj_set_width( ui_SETTINGS, 227);
lv_obj_set_height( ui_SETTINGS, 32);
lv_obj_set_x( ui_SETTINGS, 0 );
lv_obj_set_y( ui_SETTINGS, 257 );
lv_obj_set_align( ui_SETTINGS, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SETTINGS, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SETTINGS, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SETTINGS, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SETTINGS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SETTINGS, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_SETTINGS);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"SETTINGS");
lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label11, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_MENU, ui_event_MENU, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Btnbackdrop, ui_event_Btnbackdrop, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_back, ui_event_back, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GALLERY, ui_event_GALLERY, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SETTINGS, ui_event_SETTINGS, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_main, ui_event_main, LV_EVENT_ALL, NULL);
uic_Screen1 = ui_main;

}

void ui_main_screen_destroy(void)
{
   if (ui_main) lv_obj_del(ui_main);

// NULL screen variables
uic_Screen1= NULL;
ui_main= NULL;
ui_MENU= NULL;
ui_Label13= NULL;
ui_Label12= NULL;
ui_INFOSONSCREEN= NULL;
ui_Btnbackdrop= NULL;
ui_QUICKSETTINGSOVERLAY= NULL;
ui_ISO= NULL;
ui_SHUTTER= NULL;
ui_back= NULL;
ui_Image3= NULL;
ui_Label3= NULL;
ui_Label1= NULL;
ui_GRIDSWITCH= NULL;
ui_Label2= NULL;
ui_DIGITALLEVELSWITCH= NULL;
ui_Label4= NULL;
ui_COLOUR= NULL;
ui_FLASHSETTINGS= NULL;
ui_Button2= NULL;
ui_Label7= NULL;
ui_Button1= NULL;
ui_Label6= NULL;
ui_Button3= NULL;
ui_Label5= NULL;
ui_Label8= NULL;
ui_Label9= NULL;
ui_GALLERY= NULL;
ui_Label10= NULL;
ui_SETTINGS= NULL;
ui_Label11= NULL;

}
