// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: myprocam

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main
extern void ui_main_screen_init(void);
extern void ui_main_screen_destroy(void);
extern void ui_event_main( lv_event_t * e);
extern lv_obj_t *ui_main;
extern void ui_event_MENU( lv_event_t * e);
extern lv_obj_t *ui_MENU;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_INFOSONSCREEN;
extern void ui_event_Btnbackdrop( lv_event_t * e);
extern lv_obj_t *ui_Btnbackdrop;
extern lv_obj_t *ui_QUICKSETTINGSOVERLAY;
extern lv_obj_t *ui_ISO;
extern lv_obj_t *ui_SHUTTER;
extern void ui_event_back( lv_event_t * e);
extern lv_obj_t *ui_back;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_GRIDSWITCH;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_DIGITALLEVELSWITCH;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_COLOUR;
extern lv_obj_t *ui_FLASHSETTINGS;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
extern void ui_event_GALLERY( lv_event_t * e);
extern lv_obj_t *ui_GALLERY;
extern lv_obj_t *ui_Label10;
extern void ui_event_SETTINGS( lv_event_t * e);
extern lv_obj_t *ui_SETTINGS;
extern lv_obj_t *ui_Label11;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Screen1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

