// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: myprocam

#include "../ui.h"

lv_obj_t *ui_settings1 = NULL;lv_obj_t *ui_back3 = NULL;lv_obj_t *ui_Image5 = NULL;
// event funtions
void ui_event_back3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_QUICKSETTINGSOVERLAY, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Btnbackdrop, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_MENU, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_INFOSONSCREEN, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

// build funtions

void ui_settings1_screen_init(void)
{
ui_settings1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_settings1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_settings1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settings1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_back3 = lv_btn_create(ui_settings1);
lv_obj_set_width( ui_back3, 71);
lv_obj_set_height( ui_back3, 80);
lv_obj_set_x( ui_back3, -201 );
lv_obj_set_y( ui_back3, 356 );
lv_obj_set_align( ui_back3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_back3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_back3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_back3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_back3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_back3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_back3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_img_create(ui_back3);
lv_img_set_src(ui_Image5, &ui_img_2105778884);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 438
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 269
lv_obj_set_x( ui_Image5, -7 );
lv_obj_set_y( ui_Image5, 5 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image5,30);

lv_obj_add_event_cb(ui_back3, ui_event_back3, LV_EVENT_ALL, NULL);

}

void ui_settings1_screen_destroy(void)
{
   if (ui_settings1) lv_obj_del(ui_settings1);

// NULL screen variables
ui_settings1= NULL;
ui_back3= NULL;
ui_Image5= NULL;

}
