// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: myprocam

#ifndef UI_SETTINGS1_H
#define UI_SETTINGS1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settings1
extern void ui_settings1_screen_init(void);
extern void ui_settings1_screen_destroy(void);
extern lv_obj_t *ui_settings1;
extern void ui_event_back3( lv_event_t * e);
extern lv_obj_t *ui_back3;
extern lv_obj_t *ui_Image5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

