// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: myprocam

#ifndef _MYPROCAM_UI_H
#define _MYPROCAM_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_main.h"
#include "screens/ui_settings1.h"
#include "screens/ui_Gallery1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_2105778884);   // assets/Neues Projekt-3.png

// FONTS
LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_Font10);
LV_FONT_DECLARE( ui_font_Font11);
LV_FONT_DECLARE( ui_font_Font12);
LV_FONT_DECLARE( ui_font_Font2);
LV_FONT_DECLARE( ui_font_Font3);
LV_FONT_DECLARE( ui_font_Font4);
LV_FONT_DECLARE( ui_font_Font5);
LV_FONT_DECLARE( ui_font_Font6);
LV_FONT_DECLARE( ui_font_Font7);
LV_FONT_DECLARE( ui_font_Font8);
LV_FONT_DECLARE( ui_font_Font9);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
